// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: yaml.proto

package packet

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NATS 配置
type NatsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixTopic   string                 `protobuf:"bytes,1,opt,name=PrefixTopic,proto3" json:"PrefixTopic,omitempty" yaml:"prefixTopic,omitempty"`        // 订阅主题
	Endpoints     string                 `protobuf:"bytes,2,opt,name=Endpoints,proto3" json:"Endpoints,omitempty" yaml:"endpoints,omitempty"`              // url地址，多个地址用逗号分隔
	MaxReconnect  int32                  `protobuf:"varint,3,opt,name=MaxReconnect,proto3" json:"MaxReconnect,omitempty" yaml:"maxReconnect,omitempty"`    // 断线最大重连次数，0表示无限重连
	ReconnectWait int64                  `protobuf:"varint,4,opt,name=ReconnectWait,proto3" json:"ReconnectWait,omitempty" yaml:"reconnectWait,omitempty"` // 重连等待间隔(秒)
	PingInterval  int64                  `protobuf:"varint,5,opt,name=PingInterval,proto3" json:"PingInterval,omitempty" yaml:"pingInterval,omitempty"`    // 心跳检测间隔(秒)，0使用默认10秒
	DrainTimeout  int64                  `protobuf:"varint,6,opt,name=DrainTimeout,proto3" json:"DrainTimeout,omitempty" yaml:"drainTimeout,omitempty"`    // 优雅关闭等待超时(秒)，0使用默认60秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsConfig) Reset() {
	*x = NatsConfig{}
	mi := &file_yaml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsConfig) ProtoMessage() {}

func (x *NatsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsConfig.ProtoReflect.Descriptor instead.
func (*NatsConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{0}
}

func (x *NatsConfig) GetPrefixTopic() string {
	if x != nil {
		return x.PrefixTopic
	}
	return ""
}

func (x *NatsConfig) GetEndpoints() string {
	if x != nil {
		return x.Endpoints
	}
	return ""
}

func (x *NatsConfig) GetMaxReconnect() int32 {
	if x != nil {
		return x.MaxReconnect
	}
	return 0
}

func (x *NatsConfig) GetReconnectWait() int64 {
	if x != nil {
		return x.ReconnectWait
	}
	return 0
}

func (x *NatsConfig) GetPingInterval() int64 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

func (x *NatsConfig) GetDrainTimeout() int64 {
	if x != nil {
		return x.DrainTimeout
	}
	return 0
}

// 消息队列配置
type MsgQueueConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nats          *NatsConfig            `protobuf:"bytes,1,opt,name=Nats,proto3" json:"Nats,omitempty" yaml:"nats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgQueueConfig) Reset() {
	*x = MsgQueueConfig{}
	mi := &file_yaml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgQueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQueueConfig) ProtoMessage() {}

func (x *MsgQueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQueueConfig.ProtoReflect.Descriptor instead.
func (*MsgQueueConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{1}
}

func (x *MsgQueueConfig) GetNats() *NatsConfig {
	if x != nil {
		return x.Nats
	}
	return nil
}

// ETCD 配置
type EtcdConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixTopic   string                 `protobuf:"bytes,1,opt,name=PrefixTopic,proto3" json:"PrefixTopic,omitempty" yaml:"prefixTopic,omitempty"` // 订阅主题
	Endpoints     []string               `protobuf:"bytes,2,rep,name=Endpoints,proto3" json:"Endpoints,omitempty" yaml:"endpoints,omitempty"`       // etcd 地址列表
	KeepAlive     int64                  `protobuf:"varint,3,opt,name=KeepAlive,proto3" json:"KeepAlive,omitempty" yaml:"keepAlive,omitempty"`      // 租赁保活时长
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdConfig) Reset() {
	*x = EtcdConfig{}
	mi := &file_yaml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdConfig) ProtoMessage() {}

func (x *EtcdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdConfig.ProtoReflect.Descriptor instead.
func (*EtcdConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{2}
}

func (x *EtcdConfig) GetPrefixTopic() string {
	if x != nil {
		return x.PrefixTopic
	}
	return ""
}

func (x *EtcdConfig) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *EtcdConfig) GetKeepAlive() int64 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

// 服务发现与注册配置
type DiscoveryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etcd          *EtcdConfig            `protobuf:"bytes,1,opt,name=Etcd,proto3" json:"Etcd,omitempty" yaml:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryConfig) Reset() {
	*x = DiscoveryConfig{}
	mi := &file_yaml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryConfig) ProtoMessage() {}

func (x *DiscoveryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryConfig.ProtoReflect.Descriptor instead.
func (*DiscoveryConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryConfig) GetEtcd() *EtcdConfig {
	if x != nil {
		return x.Etcd
	}
	return nil
}

// 数据库节点配置
type DbConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardsId      uint32                 `protobuf:"varint,1,opt,name=ShardsId,proto3" json:"ShardsId,omitempty" yaml:"shardsId,omitempty"`
	DbName        string                 `protobuf:"bytes,2,opt,name=DbName,proto3" json:"DbName,omitempty" yaml:"dbName,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=Db,proto3" json:"Db,omitempty" yaml:"db,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty" yaml:"user,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty" yaml:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,6,opt,name=Ip,proto3" json:"Ip,omitempty" yaml:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,7,opt,name=Port,proto3" json:"Port,omitempty" yaml:"port,omitempty"`
	Prefix        string                 `protobuf:"bytes,8,opt,name=Prefix,proto3" json:"Prefix,omitempty" yaml:"prefix,omitempty"`
	Slaves        map[int32]*DbConfig    `protobuf:"bytes,9,rep,name=Slaves,proto3" json:"Slaves,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" yaml:"slaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbConfig) Reset() {
	*x = DbConfig{}
	mi := &file_yaml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbConfig) ProtoMessage() {}

func (x *DbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbConfig.ProtoReflect.Descriptor instead.
func (*DbConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{4}
}

func (x *DbConfig) GetShardsId() uint32 {
	if x != nil {
		return x.ShardsId
	}
	return 0
}

func (x *DbConfig) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DbConfig) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *DbConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DbConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DbConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DbConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DbConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *DbConfig) GetSlaves() map[int32]*DbConfig {
	if x != nil {
		return x.Slaves
	}
	return nil
}

// 数据库配置
type MysqlConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardsSize    int64                  `protobuf:"varint,1,opt,name=ShardsSize,proto3" json:"ShardsSize,omitempty" yaml:"shardsSize,omitempty"`
	Globals       []*DbConfig            `protobuf:"bytes,2,rep,name=Globals,proto3" json:"Globals,omitempty" yaml:"globals,omitempty"`
	Shards        []*DbConfig            `protobuf:"bytes,3,rep,name=Shards,proto3" json:"Shards,omitempty" yaml:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlConfig) Reset() {
	*x = MysqlConfig{}
	mi := &file_yaml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlConfig) ProtoMessage() {}

func (x *MysqlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlConfig.ProtoReflect.Descriptor instead.
func (*MysqlConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{5}
}

func (x *MysqlConfig) GetShardsSize() int64 {
	if x != nil {
		return x.ShardsSize
	}
	return 0
}

func (x *MysqlConfig) GetGlobals() []*DbConfig {
	if x != nil {
		return x.Globals
	}
	return nil
}

func (x *MysqlConfig) GetShards() []*DbConfig {
	if x != nil {
		return x.Shards
	}
	return nil
}

type RedisConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardsSize    int64                  `protobuf:"varint,1,opt,name=ShardsSize,proto3" json:"ShardsSize,omitempty" yaml:"shardsSize,omitempty"`
	Globals       []*DbConfig            `protobuf:"bytes,2,rep,name=Globals,proto3" json:"Globals,omitempty" yaml:"globals,omitempty"`
	Shards        []*DbConfig            `protobuf:"bytes,3,rep,name=Shards,proto3" json:"Shards,omitempty" yaml:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisConfig) Reset() {
	*x = RedisConfig{}
	mi := &file_yaml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConfig) ProtoMessage() {}

func (x *RedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConfig.ProtoReflect.Descriptor instead.
func (*RedisConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{6}
}

func (x *RedisConfig) GetShardsSize() int64 {
	if x != nil {
		return x.ShardsSize
	}
	return 0
}

func (x *RedisConfig) GetGlobals() []*DbConfig {
	if x != nil {
		return x.Globals
	}
	return nil
}

func (x *RedisConfig) GetShards() []*DbConfig {
	if x != nil {
		return x.Shards
	}
	return nil
}

// 配置中心配置
type TableConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfPath      string                 `protobuf:"bytes,1,opt,name=ConfPath,proto3" json:"ConfPath,omitempty" yaml:"confPath,omitempty"` // conf文件目录
	XlsxPath      string                 `protobuf:"bytes,2,opt,name=XlsxPath,proto3" json:"XlsxPath,omitempty" yaml:"xlsxPath,omitempty"` // 表目录
	ConfExt       string                 `protobuf:"bytes,3,opt,name=ConfExt,proto3" json:"ConfExt,omitempty" yaml:"confExt,omitempty"`    // 表扩展名
	Etcd          *EtcdConfig            `protobuf:"bytes,4,opt,name=Etcd,proto3" json:"Etcd,omitempty" yaml:"etcd,omitempty"`             // etcd 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableConfig) Reset() {
	*x = TableConfig{}
	mi := &file_yaml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableConfig) ProtoMessage() {}

func (x *TableConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableConfig.ProtoReflect.Descriptor instead.
func (*TableConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{7}
}

func (x *TableConfig) GetConfPath() string {
	if x != nil {
		return x.ConfPath
	}
	return ""
}

func (x *TableConfig) GetXlsxPath() string {
	if x != nil {
		return x.XlsxPath
	}
	return ""
}

func (x *TableConfig) GetConfExt() string {
	if x != nil {
		return x.ConfExt
	}
	return ""
}

func (x *TableConfig) GetEtcd() *EtcdConfig {
	if x != nil {
		return x.Etcd
	}
	return nil
}

// 公共配置
type CommonConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=Env,proto3" json:"Env,omitempty" yaml:"env,omitempty"`
	IsOpenPprof   bool                   `protobuf:"varint,2,opt,name=IsOpenPprof,proto3" json:"IsOpenPprof,omitempty" yaml:"isOpenPprof,omitempty"`
	JwtSecret     string                 `protobuf:"bytes,3,opt,name=JwtSecret,proto3" json:"JwtSecret,omitempty" yaml:"jwtSecret,omitempty"`
	AesSecret     string                 `protobuf:"bytes,4,opt,name=AesSecret,proto3" json:"AesSecret,omitempty" yaml:"aesSecret,omitempty"`
	UidModValue   uint64                 `protobuf:"varint,5,opt,name=UidModValue,proto3" json:"UidModValue,omitempty" yaml:"uidModValue,omitempty"`
	PayPort       int32                  `protobuf:"varint,6,opt,name=PayPort,proto3" json:"PayPort,omitempty" yaml:"payPort,omitempty"`
	GeoDbPath     string                 `protobuf:"bytes,7,opt,name=GeoDbPath,proto3" json:"GeoDbPath,omitempty" yaml:"geoDbPath,omitempty"` // GeoLite2-City.mmdb 文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonConfig) Reset() {
	*x = CommonConfig{}
	mi := &file_yaml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonConfig) ProtoMessage() {}

func (x *CommonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonConfig.ProtoReflect.Descriptor instead.
func (*CommonConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{8}
}

func (x *CommonConfig) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *CommonConfig) GetIsOpenPprof() bool {
	if x != nil {
		return x.IsOpenPprof
	}
	return false
}

func (x *CommonConfig) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *CommonConfig) GetAesSecret() string {
	if x != nil {
		return x.AesSecret
	}
	return ""
}

func (x *CommonConfig) GetUidModValue() uint64 {
	if x != nil {
		return x.UidModValue
	}
	return 0
}

func (x *CommonConfig) GetPayPort() int32 {
	if x != nil {
		return x.PayPort
	}
	return 0
}

func (x *CommonConfig) GetGeoDbPath() string {
	if x != nil {
		return x.GeoDbPath
	}
	return ""
}

type LoggerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=Mode,proto3" json:"Mode,omitempty" yaml:"mode,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty" yaml:"path,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=Level,proto3" json:"Level,omitempty" yaml:"level,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=Format,proto3" json:"Format,omitempty" yaml:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerConfig) Reset() {
	*x = LoggerConfig{}
	mi := &file_yaml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerConfig) ProtoMessage() {}

func (x *LoggerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerConfig.ProtoReflect.Descriptor instead.
func (*LoggerConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{9}
}

func (x *LoggerConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *LoggerConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoggerConfig) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoggerConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 节点配置
type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty" yaml:"type,omitempty"`            // 节点类型
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" yaml:"name,omitempty"`             // 节点名字
	Id            uint32                 `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty" yaml:"id,omitempty"`                  // 节点id
	Ip            string                 `protobuf:"bytes,4,opt,name=Ip,proto3" json:"Ip,omitempty" yaml:"ip,omitempty"`                   // ip 地址
	Port          int32                  `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty" yaml:"port,omitempty"`            // 端口
	LogLevel      string                 `protobuf:"bytes,6,opt,name=LogLevel,proto3" json:"LogLevel,omitempty" yaml:"logLevel,omitempty"` // 日志等级
	LogPath       string                 `protobuf:"bytes,7,opt,name=LogPath,proto3" json:"LogPath,omitempty" yaml:"logPath,omitempty"`    // 日志目录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_yaml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_yaml_proto_rawDescGZIP(), []int{10}
}

func (x *NodeConfig) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeConfig) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeConfig) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *NodeConfig) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

var File_yaml_proto protoreflect.FileDescriptor

const file_yaml_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"yaml.proto\"\xde\x01\n" +
	"\n" +
	"NatsConfig\x12 \n" +
	"\vPrefixTopic\x18\x01 \x01(\tR\vPrefixTopic\x12\x1c\n" +
	"\tEndpoints\x18\x02 \x01(\tR\tEndpoints\x12\"\n" +
	"\fMaxReconnect\x18\x03 \x01(\x05R\fMaxReconnect\x12$\n" +
	"\rReconnectWait\x18\x04 \x01(\x03R\rReconnectWait\x12\"\n" +
	"\fPingInterval\x18\x05 \x01(\x03R\fPingInterval\x12\"\n" +
	"\fDrainTimeout\x18\x06 \x01(\x03R\fDrainTimeout\"1\n" +
	"\x0eMsgQueueConfig\x12\x1f\n" +
	"\x04Nats\x18\x01 \x01(\v2\v.NatsConfigR\x04Nats\"j\n" +
	"\n" +
	"EtcdConfig\x12 \n" +
	"\vPrefixTopic\x18\x01 \x01(\tR\vPrefixTopic\x12\x1c\n" +
	"\tEndpoints\x18\x02 \x03(\tR\tEndpoints\x12\x1c\n" +
	"\tKeepAlive\x18\x03 \x01(\x03R\tKeepAlive\"2\n" +
	"\x0fDiscoveryConfig\x12\x1f\n" +
	"\x04Etcd\x18\x01 \x01(\v2\v.EtcdConfigR\x04Etcd\"\xaf\x02\n" +
	"\bDbConfig\x12\x1a\n" +
	"\bShardsId\x18\x01 \x01(\rR\bShardsId\x12\x16\n" +
	"\x06DbName\x18\x02 \x01(\tR\x06DbName\x12\x0e\n" +
	"\x02Db\x18\x03 \x01(\x05R\x02Db\x12\x12\n" +
	"\x04User\x18\x04 \x01(\tR\x04User\x12\x1a\n" +
	"\bPassword\x18\x05 \x01(\tR\bPassword\x12\x0e\n" +
	"\x02Ip\x18\x06 \x01(\tR\x02Ip\x12\x12\n" +
	"\x04Port\x18\a \x01(\x05R\x04Port\x12\x16\n" +
	"\x06Prefix\x18\b \x01(\tR\x06Prefix\x12-\n" +
	"\x06Slaves\x18\t \x03(\v2\x15.DbConfig.SlavesEntryR\x06Slaves\x1aD\n" +
	"\vSlavesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.DbConfigR\x05value:\x028\x01\"u\n" +
	"\vMysqlConfig\x12\x1e\n" +
	"\n" +
	"ShardsSize\x18\x01 \x01(\x03R\n" +
	"ShardsSize\x12#\n" +
	"\aGlobals\x18\x02 \x03(\v2\t.DbConfigR\aGlobals\x12!\n" +
	"\x06Shards\x18\x03 \x03(\v2\t.DbConfigR\x06Shards\"u\n" +
	"\vRedisConfig\x12\x1e\n" +
	"\n" +
	"ShardsSize\x18\x01 \x01(\x03R\n" +
	"ShardsSize\x12#\n" +
	"\aGlobals\x18\x02 \x03(\v2\t.DbConfigR\aGlobals\x12!\n" +
	"\x06Shards\x18\x03 \x03(\v2\t.DbConfigR\x06Shards\"\x80\x01\n" +
	"\vTableConfig\x12\x1a\n" +
	"\bConfPath\x18\x01 \x01(\tR\bConfPath\x12\x1a\n" +
	"\bXlsxPath\x18\x02 \x01(\tR\bXlsxPath\x12\x18\n" +
	"\aConfExt\x18\x03 \x01(\tR\aConfExt\x12\x1f\n" +
	"\x04Etcd\x18\x04 \x01(\v2\v.EtcdConfigR\x04Etcd\"\xd8\x01\n" +
	"\fCommonConfig\x12\x10\n" +
	"\x03Env\x18\x01 \x01(\tR\x03Env\x12 \n" +
	"\vIsOpenPprof\x18\x02 \x01(\bR\vIsOpenPprof\x12\x1c\n" +
	"\tJwtSecret\x18\x03 \x01(\tR\tJwtSecret\x12\x1c\n" +
	"\tAesSecret\x18\x04 \x01(\tR\tAesSecret\x12 \n" +
	"\vUidModValue\x18\x05 \x01(\x04R\vUidModValue\x12\x18\n" +
	"\aPayPort\x18\x06 \x01(\x05R\aPayPort\x12\x1c\n" +
	"\tGeoDbPath\x18\a \x01(\tR\tGeoDbPath\"d\n" +
	"\fLoggerConfig\x12\x12\n" +
	"\x04Mode\x18\x01 \x01(\tR\x04Mode\x12\x12\n" +
	"\x04Path\x18\x02 \x01(\tR\x04Path\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\tR\x05Level\x12\x16\n" +
	"\x06Format\x18\x04 \x01(\tR\x06Format\"\x9e\x01\n" +
	"\n" +
	"NodeConfig\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\rR\x04Type\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x0e\n" +
	"\x02Id\x18\x03 \x01(\rR\x02Id\x12\x0e\n" +
	"\x02Ip\x18\x04 \x01(\tR\x02Ip\x12\x12\n" +
	"\x04Port\x18\x05 \x01(\x05R\x04Port\x12\x1a\n" +
	"\bLogLevel\x18\x06 \x01(\tR\bLogLevel\x12\x18\n" +
	"\aLogPath\x18\a \x01(\tR\aLogPathB\x12Z\x10framework/packetb\x06proto3"

var (
	file_yaml_proto_rawDescOnce sync.Once
	file_yaml_proto_rawDescData []byte
)

func file_yaml_proto_rawDescGZIP() []byte {
	file_yaml_proto_rawDescOnce.Do(func() {
		file_yaml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yaml_proto_rawDesc), len(file_yaml_proto_rawDesc)))
	})
	return file_yaml_proto_rawDescData
}

var file_yaml_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_yaml_proto_goTypes = []any{
	(*NatsConfig)(nil),      // 0: NatsConfig
	(*MsgQueueConfig)(nil),  // 1: MsgQueueConfig
	(*EtcdConfig)(nil),      // 2: EtcdConfig
	(*DiscoveryConfig)(nil), // 3: DiscoveryConfig
	(*DbConfig)(nil),        // 4: DbConfig
	(*MysqlConfig)(nil),     // 5: MysqlConfig
	(*RedisConfig)(nil),     // 6: RedisConfig
	(*TableConfig)(nil),     // 7: TableConfig
	(*CommonConfig)(nil),    // 8: CommonConfig
	(*LoggerConfig)(nil),    // 9: LoggerConfig
	(*NodeConfig)(nil),      // 10: NodeConfig
	nil,                     // 11: DbConfig.SlavesEntry
}
var file_yaml_proto_depIdxs = []int32{
	0,  // 0: MsgQueueConfig.Nats:type_name -> NatsConfig
	2,  // 1: DiscoveryConfig.Etcd:type_name -> EtcdConfig
	11, // 2: DbConfig.Slaves:type_name -> DbConfig.SlavesEntry
	4,  // 3: MysqlConfig.Globals:type_name -> DbConfig
	4,  // 4: MysqlConfig.Shards:type_name -> DbConfig
	4,  // 5: RedisConfig.Globals:type_name -> DbConfig
	4,  // 6: RedisConfig.Shards:type_name -> DbConfig
	2,  // 7: TableConfig.Etcd:type_name -> EtcdConfig
	4,  // 8: DbConfig.SlavesEntry.value:type_name -> DbConfig
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_yaml_proto_init() }
func file_yaml_proto_init() {
	if File_yaml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yaml_proto_rawDesc), len(file_yaml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yaml_proto_goTypes,
		DependencyIndexes: file_yaml_proto_depIdxs,
		MessageInfos:      file_yaml_proto_msgTypes,
	}.Build()
	File_yaml_proto = out.File
	file_yaml_proto_goTypes = nil
	file_yaml_proto_depIdxs = nil
}
