//
// 本代码由cfgtool工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: enum.gen.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CurrencyNone Currency = 0     // 货币类型-空
	Currency_USD          Currency = 1     // 货币类型-美元
	Currency_CAD          Currency = 2     // 货币类型-加元
	Currency_BTC          Currency = 10000 // 数字货币-比特币
	Currency_USDT         Currency = 10001 // 数字货币-泰达币
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0:     "CurrencyNone",
		1:     "USD",
		2:     "CAD",
		10000: "BTC",
		10001: "USDT",
	}
	Currency_value = map[string]int32{
		"CurrencyNone": 0,
		"USD":          1,
		"CAD":          2,
		"BTC":          10000,
		"USDT":         10001,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{0}
}

type DepositStatus int32

const (
	DepositStatus_DepositStatusDelete  DepositStatus = 0 // 充值状态-已删除
	DepositStatus_DepositStatusWait    DepositStatus = 1 // 充值状态-待支付
	DepositStatus_DepositStatusSuccess DepositStatus = 2 // 充值状态-已支付
)

// Enum value maps for DepositStatus.
var (
	DepositStatus_name = map[int32]string{
		0: "DepositStatusDelete",
		1: "DepositStatusWait",
		2: "DepositStatusSuccess",
	}
	DepositStatus_value = map[string]int32{
		"DepositStatusDelete":  0,
		"DepositStatusWait":    1,
		"DepositStatusSuccess": 2,
	}
)

func (x DepositStatus) Enum() *DepositStatus {
	p := new(DepositStatus)
	*p = x
	return p
}

func (x DepositStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[1].Descriptor()
}

func (DepositStatus) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[1]
}

func (x DepositStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositStatus.Descriptor instead.
func (DepositStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{1}
}

type GameType int32

const (
	GameType_GameTypeNone GameType = 0   // 游戏类型-空
	GameType_Aviator      GameType = 1   // 游戏类型-Spribe-Aviator
	GameType_Dice         GameType = 2   // 游戏类型-Spribe-Dice
	GameType_Goal         GameType = 3   // 游戏类型-Spribe-Goal
	GameType_Plinko       GameType = 4   // 游戏类型-Spribe-Plinko
	GameType_Mines        GameType = 5   // 游戏类型-Spribe-Mines
	GameType_HiLo         GameType = 6   // 游戏类型-Spribe-HiLo
	GameType_Keno         GameType = 7   // 游戏类型-Spribe-Keno
	GameType_MiniRoulette GameType = 8   // 游戏类型-Spribe-MiniRoulette
	GameType_Hotline      GameType = 9   // 游戏类型-Spribe-Hotline
	GameType_Balloon      GameType = 10  // 游戏类型-Spribe-Balloon
	GameType_Keno80       GameType = 11  // 游戏类型-Spribe-Keno80
	GameType_Trader       GameType = 12  // 游戏类型-Spribe-Trader
	GameType_CrystalFall  GameType = 13  // 游戏类型-Spribe-CrystalFall
	GameType_NeoVegas     GameType = 14  // 游戏类型-Spribe-NeoVegas
	GameType_GatesOfEgypt GameType = 15  // 游戏类型-Spribe-GatesOfEgypt
	GameType_Twist        GameType = 100 // 游戏类型-Inout-Twist
	GameType_Inout_Plinko GameType = 101 // 游戏类型-Inout-Plinko
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0:   "GameTypeNone",
		1:   "Aviator",
		2:   "Dice",
		3:   "Goal",
		4:   "Plinko",
		5:   "Mines",
		6:   "HiLo",
		7:   "Keno",
		8:   "MiniRoulette",
		9:   "Hotline",
		10:  "Balloon",
		11:  "Keno80",
		12:  "Trader",
		13:  "CrystalFall",
		14:  "NeoVegas",
		15:  "GatesOfEgypt",
		100: "Twist",
		101: "Inout_Plinko",
	}
	GameType_value = map[string]int32{
		"GameTypeNone": 0,
		"Aviator":      1,
		"Dice":         2,
		"Goal":         3,
		"Plinko":       4,
		"Mines":        5,
		"HiLo":         6,
		"Keno":         7,
		"MiniRoulette": 8,
		"Hotline":      9,
		"Balloon":      10,
		"Keno80":       11,
		"Trader":       12,
		"CrystalFall":  13,
		"NeoVegas":     14,
		"GatesOfEgypt": 15,
		"Twist":        100,
		"Inout_Plinko": 101,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[2].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[2]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{2}
}

type LangType int32

const (
	LangType_LangTypeNone LangType = 0 // 语言类型-空
	LangType_ZH           LangType = 1 // 语言类型-汉语
	LangType_AZ           LangType = 2 // 语言类型-阿塞拜疆语
)

// Enum value maps for LangType.
var (
	LangType_name = map[int32]string{
		0: "LangTypeNone",
		1: "ZH",
		2: "AZ",
	}
	LangType_value = map[string]int32{
		"LangTypeNone": 0,
		"ZH":           1,
		"AZ":           2,
	}
)

func (x LangType) Enum() *LangType {
	p := new(LangType)
	*p = x
	return p
}

func (x LangType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LangType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[3].Descriptor()
}

func (LangType) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[3]
}

func (x LangType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LangType.Descriptor instead.
func (LangType) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{3}
}

type LoginType int32

const (
	LoginType_LoginTypeNone LoginType = 0 // 登录类型-空
	LoginType_Guest         LoginType = 1 // 登录类型-游客登录
	LoginType_Account       LoginType = 2 // 登录类型-账号
	LoginType_Apple         LoginType = 3 // 登录类型-苹果
	LoginType_Google        LoginType = 4 // 登录类型-谷歌
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LoginTypeNone",
		1: "Guest",
		2: "Account",
		3: "Apple",
		4: "Google",
	}
	LoginType_value = map[string]int32{
		"LoginTypeNone": 0,
		"Guest":         1,
		"Account":       2,
		"Apple":         3,
		"Google":        4,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[4].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[4]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{4}
}

type OrderStatus int32

const (
	OrderStatus_Cancel OrderStatus = 0 // 订单状态-撤单
	OrderStatus_Insert OrderStatus = 1 // 订单状态-下单
	OrderStatus_Update OrderStatus = 2 // 订单状态-改单
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "Cancel",
		1: "Insert",
		2: "Update",
	}
	OrderStatus_value = map[string]int32{
		"Cancel": 0,
		"Insert": 1,
		"Update": 2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[5].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[5]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{5}
}

type Platform int32

const (
	Platform_PlatformTypeNone Platform = 0 // 平台类型-空
	Platform_Mobile           Platform = 1 // 平台类型-Mobile
	Platform_Desktop          Platform = 2 // 平台类型-Desktop
	Platform_Web              Platform = 3 // 平台类型-Web
	Platform_Ios              Platform = 4 // 平台类型-Ios
	Platform_Android          Platform = 5 // 平台类型-Android
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PlatformTypeNone",
		1: "Mobile",
		2: "Desktop",
		3: "Web",
		4: "Ios",
		5: "Android",
	}
	Platform_value = map[string]int32{
		"PlatformTypeNone": 0,
		"Mobile":           1,
		"Desktop":          2,
		"Web":              3,
		"Ios":              4,
		"Android":          5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[6].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[6]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{6}
}

type Provider int32

const (
	Provider_ProviderNone Provider = 0 // 供应商-无
	Provider_Spribe       Provider = 1 // 供应商-Spribe
	Provider_Inout        Provider = 2 // 供应商-Inout
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "ProviderNone",
		1: "Spribe",
		2: "Inout",
	}
	Provider_value = map[string]int32{
		"ProviderNone": 0,
		"Spribe":       1,
		"Inout":        2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[7].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[7]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{7}
}

type Reason int32

const (
	Reason_ReasonNone Reason = 0 // 原因类型-空
	Reason_Bet        Reason = 1 // 原因类型-下注
	Reason_Result     Reason = 2 // 原因类型-结算
	Reason_Revoke     Reason = 3 // 原因类型-撤单
	Reason_Recharge   Reason = 4 // 原因类型-充值
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "ReasonNone",
		1: "Bet",
		2: "Result",
		3: "Revoke",
		4: "Recharge",
	}
	Reason_value = map[string]int32{
		"ReasonNone": 0,
		"Bet":        1,
		"Result":     2,
		"Revoke":     3,
		"Recharge":   4,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[8].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[8]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{8}
}

type WithdrawStatus int32

const (
	WithdrawStatus_WithdrawStatusDelete  WithdrawStatus = 0 // 提现状态-已删除
	WithdrawStatus_WithdrawStatusWait    WithdrawStatus = 1 // 提现状态-待支付
	WithdrawStatus_WithdrawStatusSuccess WithdrawStatus = 2 // 提现状态-已支付
)

// Enum value maps for WithdrawStatus.
var (
	WithdrawStatus_name = map[int32]string{
		0: "WithdrawStatusDelete",
		1: "WithdrawStatusWait",
		2: "WithdrawStatusSuccess",
	}
	WithdrawStatus_value = map[string]int32{
		"WithdrawStatusDelete":  0,
		"WithdrawStatusWait":    1,
		"WithdrawStatusSuccess": 2,
	}
)

func (x WithdrawStatus) Enum() *WithdrawStatus {
	p := new(WithdrawStatus)
	*p = x
	return p
}

func (x WithdrawStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WithdrawStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[9].Descriptor()
}

func (WithdrawStatus) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[9]
}

func (x WithdrawStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WithdrawStatus.Descriptor instead.
func (WithdrawStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{9}
}

var File_enum_gen_proto protoreflect.FileDescriptor

var file_enum_gen_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2a, 0x43, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41,
	0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x03, 0x42, 0x54, 0x43, 0x10, 0x90, 0x4e, 0x12, 0x09, 0x0a,
	0x04, 0x55, 0x53, 0x44, 0x54, 0x10, 0x91, 0x4e, 0x2a, 0x59, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x57, 0x61, 0x69, 0x74, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x02, 0x2a, 0xfa, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x76, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x6f, 0x61,
	0x6c, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x6c, 0x69, 0x6e, 0x6b, 0x6f, 0x10, 0x04, 0x12,
	0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x73, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x69,
	0x4c, 0x6f, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x65, 0x6e, 0x6f, 0x10, 0x07, 0x12, 0x10,
	0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x69, 0x52, 0x6f, 0x75, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x10, 0x08,
	0x12, 0x0b, 0x0a, 0x07, 0x48, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x09, 0x12, 0x0b, 0x0a,
	0x07, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x6f, 0x6e, 0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x65,
	0x6e, 0x6f, 0x38, 0x30, 0x10, 0x0b, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x46, 0x61, 0x6c,
	0x6c, 0x10, 0x0d, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x65, 0x6f, 0x56, 0x65, 0x67, 0x61, 0x73, 0x10,
	0x0e, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x73, 0x4f, 0x66, 0x45, 0x67, 0x79, 0x70,
	0x74, 0x10, 0x0f, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x77, 0x69, 0x73, 0x74, 0x10, 0x64, 0x12, 0x10,
	0x0a, 0x0c, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x5f, 0x50, 0x6c, 0x69, 0x6e, 0x6b, 0x6f, 0x10, 0x65,
	0x2a, 0x2c, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x4c, 0x61, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x5a, 0x48, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x5a, 0x10, 0x02, 0x2a, 0x4d,
	0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x47, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x04, 0x2a, 0x31, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02,
	0x2a, 0x58, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x10,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x57,
	0x65, 0x62, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x6f, 0x73, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x05, 0x2a, 0x33, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x70, 0x72, 0x69,
	0x62, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x10, 0x02, 0x2a,
	0x47, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x65, 0x74,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x10, 0x04, 0x2a, 0x5d, 0x0a, 0x0e, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x61, 0x69, 0x74, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_gen_proto_rawDescOnce sync.Once
	file_enum_gen_proto_rawDescData = file_enum_gen_proto_rawDesc
)

func file_enum_gen_proto_rawDescGZIP() []byte {
	file_enum_gen_proto_rawDescOnce.Do(func() {
		file_enum_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_gen_proto_rawDescData)
	})
	return file_enum_gen_proto_rawDescData
}

var file_enum_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_enum_gen_proto_goTypes = []interface{}{
	(Currency)(0),       // 0: bit_casino_golang.Currency
	(DepositStatus)(0),  // 1: bit_casino_golang.DepositStatus
	(GameType)(0),       // 2: bit_casino_golang.GameType
	(LangType)(0),       // 3: bit_casino_golang.LangType
	(LoginType)(0),      // 4: bit_casino_golang.LoginType
	(OrderStatus)(0),    // 5: bit_casino_golang.OrderStatus
	(Platform)(0),       // 6: bit_casino_golang.Platform
	(Provider)(0),       // 7: bit_casino_golang.Provider
	(Reason)(0),         // 8: bit_casino_golang.Reason
	(WithdrawStatus)(0), // 9: bit_casino_golang.WithdrawStatus
}
var file_enum_gen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_gen_proto_init() }
func file_enum_gen_proto_init() {
	if File_enum_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_gen_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_gen_proto_goTypes,
		DependencyIndexes: file_enum_gen_proto_depIdxs,
		EnumInfos:         file_enum_gen_proto_enumTypes,
	}.Build()
	File_enum_gen_proto = out.File
	file_enum_gen_proto_rawDesc = nil
	file_enum_gen_proto_goTypes = nil
	file_enum_gen_proto_depIdxs = nil
}
