//
// 本代码由cfgtool工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: table.gen.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrencyExchangeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                             // 唯一ID
	Currency Currency `protobuf:"varint,2,opt,name=Currency,proto3,enum=bit_casino_golang.Currency" json:"Currency,omitempty"` // 货币类型
	Ratio    int64    `protobuf:"varint,3,opt,name=Ratio,proto3" json:"Ratio,omitempty"`                                       // 比率
}

func (x *CurrencyExchangeConfig) Reset() {
	*x = CurrencyExchangeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyExchangeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyExchangeConfig) ProtoMessage() {}

func (x *CurrencyExchangeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyExchangeConfig.ProtoReflect.Descriptor instead.
func (*CurrencyExchangeConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyExchangeConfig) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CurrencyExchangeConfig) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CurrencyNone
}

func (x *CurrencyExchangeConfig) GetRatio() int64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

type CurrencyExchangeConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*CurrencyExchangeConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *CurrencyExchangeConfigAry) Reset() {
	*x = CurrencyExchangeConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyExchangeConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyExchangeConfigAry) ProtoMessage() {}

func (x *CurrencyExchangeConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyExchangeConfigAry.ProtoReflect.Descriptor instead.
func (*CurrencyExchangeConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyExchangeConfigAry) GetAry() []*CurrencyExchangeConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type GameConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32     `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                                       // 唯一ID
	Provider     Provider   `protobuf:"varint,2,opt,name=Provider,proto3,enum=bit_casino_golang.Provider" json:"Provider,omitempty"`           // 游戏平台
	GameType     GameType   `protobuf:"varint,3,opt,name=GameType,proto3,enum=bit_casino_golang.GameType" json:"GameType,omitempty"`           // 游戏类型
	IsHot        bool       `protobuf:"varint,4,opt,name=IsHot,proto3" json:"IsHot,omitempty"`                                                 // 是否热门游戏
	BeginTime    int64      `protobuf:"varint,5,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`                                         // 游戏开始时间
	EndTime      int64      `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`                                             // 游戏结束时间
	Sort         int32      `protobuf:"varint,7,opt,name=Sort,proto3" json:"Sort,omitempty"`                                                   // 排序值
	Version      string     `protobuf:"bytes,8,opt,name=Version,proto3" json:"Version,omitempty"`                                              // 版本控制
	Platforms    []Platform `protobuf:"varint,9,rep,packed,name=Platforms,proto3,enum=bit_casino_golang.Platform" json:"Platforms,omitempty"`  // 平台控制
	Area         string     `protobuf:"bytes,10,opt,name=Area,proto3" json:"Area,omitempty"`                                                   // 区域限制
	Currencys    []Currency `protobuf:"varint,11,rep,packed,name=Currencys,proto3,enum=bit_casino_golang.Currency" json:"Currencys,omitempty"` // 货币类型
	ProviderIcon string     `protobuf:"bytes,12,opt,name=ProviderIcon,proto3" json:"ProviderIcon,omitempty"`                                   // 游戏平台图标
	GameIcon     string     `protobuf:"bytes,13,opt,name=GameIcon,proto3" json:"GameIcon,omitempty"`                                           // 游戏图标
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{2}
}

func (x *GameConfig) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameConfig) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_ProviderNone
}

func (x *GameConfig) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeNone
}

func (x *GameConfig) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GameConfig) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *GameConfig) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GameConfig) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *GameConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GameConfig) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *GameConfig) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *GameConfig) GetCurrencys() []Currency {
	if x != nil {
		return x.Currencys
	}
	return nil
}

func (x *GameConfig) GetProviderIcon() string {
	if x != nil {
		return x.ProviderIcon
	}
	return ""
}

func (x *GameConfig) GetGameIcon() string {
	if x != nil {
		return x.GameIcon
	}
	return ""
}

type GameConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*GameConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *GameConfigAry) Reset() {
	*x = GameConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfigAry) ProtoMessage() {}

func (x *GameConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfigAry.ProtoReflect.Descriptor instead.
func (*GameConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{3}
}

func (x *GameConfigAry) GetAry() []*GameConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type GlobalConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UidBeginValue   uint64 `protobuf:"varint,1,opt,name=UidBeginValue,proto3" json:"UidBeginValue,omitempty"`    // uid开始值
	GameUrl         string `protobuf:"bytes,2,opt,name=GameUrl,proto3" json:"GameUrl,omitempty"`                 // 游戏url地址
	SpribeLaunchUrl string `protobuf:"bytes,3,opt,name=SpribeLaunchUrl,proto3" json:"SpribeLaunchUrl,omitempty"` // 游戏地址
	SpribeReturnUrl string `protobuf:"bytes,4,opt,name=SpribeReturnUrl,proto3" json:"SpribeReturnUrl,omitempty"` // 回调地址
	InoutLaunchUrl  string `protobuf:"bytes,5,opt,name=InoutLaunchUrl,proto3" json:"InoutLaunchUrl,omitempty"`   // 游戏地址
	InoutReturnUrl  string `protobuf:"bytes,6,opt,name=InoutReturnUrl,proto3" json:"InoutReturnUrl,omitempty"`   // 回调地址
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalConfig) GetUidBeginValue() uint64 {
	if x != nil {
		return x.UidBeginValue
	}
	return 0
}

func (x *GlobalConfig) GetGameUrl() string {
	if x != nil {
		return x.GameUrl
	}
	return ""
}

func (x *GlobalConfig) GetSpribeLaunchUrl() string {
	if x != nil {
		return x.SpribeLaunchUrl
	}
	return ""
}

func (x *GlobalConfig) GetSpribeReturnUrl() string {
	if x != nil {
		return x.SpribeReturnUrl
	}
	return ""
}

func (x *GlobalConfig) GetInoutLaunchUrl() string {
	if x != nil {
		return x.InoutLaunchUrl
	}
	return ""
}

func (x *GlobalConfig) GetInoutReturnUrl() string {
	if x != nil {
		return x.InoutReturnUrl
	}
	return ""
}

type GlobalConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*GlobalConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *GlobalConfigAry) Reset() {
	*x = GlobalConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfigAry) ProtoMessage() {}

func (x *GlobalConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfigAry.ProtoReflect.Descriptor instead.
func (*GlobalConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{5}
}

func (x *GlobalConfigAry) GetAry() []*GlobalConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type InoutCurrencyConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency Currency `protobuf:"varint,1,opt,name=Currency,proto3,enum=bit_casino_golang.Currency" json:"Currency,omitempty"` // 货币类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 货币代码
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 货币名字
}

func (x *InoutCurrencyConfig) Reset() {
	*x = InoutCurrencyConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutCurrencyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutCurrencyConfig) ProtoMessage() {}

func (x *InoutCurrencyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutCurrencyConfig.ProtoReflect.Descriptor instead.
func (*InoutCurrencyConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{6}
}

func (x *InoutCurrencyConfig) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CurrencyNone
}

func (x *InoutCurrencyConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InoutCurrencyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InoutCurrencyConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*InoutCurrencyConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *InoutCurrencyConfigAry) Reset() {
	*x = InoutCurrencyConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutCurrencyConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutCurrencyConfigAry) ProtoMessage() {}

func (x *InoutCurrencyConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutCurrencyConfigAry.ProtoReflect.Descriptor instead.
func (*InoutCurrencyConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{7}
}

func (x *InoutCurrencyConfigAry) GetAry() []*InoutCurrencyConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type InoutGameConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType GameType `protobuf:"varint,1,opt,name=GameType,proto3,enum=bit_casino_golang.GameType" json:"GameType,omitempty"` // 游戏类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 游戏识别
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 名字
}

func (x *InoutGameConfig) Reset() {
	*x = InoutGameConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutGameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutGameConfig) ProtoMessage() {}

func (x *InoutGameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutGameConfig.ProtoReflect.Descriptor instead.
func (*InoutGameConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{8}
}

func (x *InoutGameConfig) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeNone
}

func (x *InoutGameConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InoutGameConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InoutGameConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*InoutGameConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *InoutGameConfigAry) Reset() {
	*x = InoutGameConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutGameConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutGameConfigAry) ProtoMessage() {}

func (x *InoutGameConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutGameConfigAry.ProtoReflect.Descriptor instead.
func (*InoutGameConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{9}
}

func (x *InoutGameConfigAry) GetAry() []*InoutGameConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type InoutLangConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LangType LangType `protobuf:"varint,1,opt,name=LangType,proto3,enum=bit_casino_golang.LangType" json:"LangType,omitempty"` // 语言类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 语言代码
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 名字
}

func (x *InoutLangConfig) Reset() {
	*x = InoutLangConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutLangConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutLangConfig) ProtoMessage() {}

func (x *InoutLangConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutLangConfig.ProtoReflect.Descriptor instead.
func (*InoutLangConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{10}
}

func (x *InoutLangConfig) GetLangType() LangType {
	if x != nil {
		return x.LangType
	}
	return LangType_LangTypeNone
}

func (x *InoutLangConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InoutLangConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InoutLangConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*InoutLangConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *InoutLangConfigAry) Reset() {
	*x = InoutLangConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutLangConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutLangConfigAry) ProtoMessage() {}

func (x *InoutLangConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutLangConfigAry.ProtoReflect.Descriptor instead.
func (*InoutLangConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{11}
}

func (x *InoutLangConfigAry) GetAry() []*InoutLangConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type SpribeCurrencyConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency Currency `protobuf:"varint,1,opt,name=Currency,proto3,enum=bit_casino_golang.Currency" json:"Currency,omitempty"` // 货币类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 货币代码
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 货币名字
}

func (x *SpribeCurrencyConfig) Reset() {
	*x = SpribeCurrencyConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeCurrencyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeCurrencyConfig) ProtoMessage() {}

func (x *SpribeCurrencyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeCurrencyConfig.ProtoReflect.Descriptor instead.
func (*SpribeCurrencyConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{12}
}

func (x *SpribeCurrencyConfig) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CurrencyNone
}

func (x *SpribeCurrencyConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SpribeCurrencyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SpribeCurrencyConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*SpribeCurrencyConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *SpribeCurrencyConfigAry) Reset() {
	*x = SpribeCurrencyConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeCurrencyConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeCurrencyConfigAry) ProtoMessage() {}

func (x *SpribeCurrencyConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeCurrencyConfigAry.ProtoReflect.Descriptor instead.
func (*SpribeCurrencyConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{13}
}

func (x *SpribeCurrencyConfigAry) GetAry() []*SpribeCurrencyConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type SpribeGameConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType GameType `protobuf:"varint,1,opt,name=GameType,proto3,enum=bit_casino_golang.GameType" json:"GameType,omitempty"` // 游戏类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 游戏识别
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 名字
}

func (x *SpribeGameConfig) Reset() {
	*x = SpribeGameConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeGameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeGameConfig) ProtoMessage() {}

func (x *SpribeGameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeGameConfig.ProtoReflect.Descriptor instead.
func (*SpribeGameConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{14}
}

func (x *SpribeGameConfig) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeNone
}

func (x *SpribeGameConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SpribeGameConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SpribeGameConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*SpribeGameConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *SpribeGameConfigAry) Reset() {
	*x = SpribeGameConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeGameConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeGameConfigAry) ProtoMessage() {}

func (x *SpribeGameConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeGameConfigAry.ProtoReflect.Descriptor instead.
func (*SpribeGameConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{15}
}

func (x *SpribeGameConfigAry) GetAry() []*SpribeGameConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type SpribeLangConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LangType LangType `protobuf:"varint,1,opt,name=LangType,proto3,enum=bit_casino_golang.LangType" json:"LangType,omitempty"` // 语言类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 语言代码
	Name     string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                          // 名字
}

func (x *SpribeLangConfig) Reset() {
	*x = SpribeLangConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeLangConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeLangConfig) ProtoMessage() {}

func (x *SpribeLangConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeLangConfig.ProtoReflect.Descriptor instead.
func (*SpribeLangConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{16}
}

func (x *SpribeLangConfig) GetLangType() LangType {
	if x != nil {
		return x.LangType
	}
	return LangType_LangTypeNone
}

func (x *SpribeLangConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SpribeLangConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SpribeLangConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*SpribeLangConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *SpribeLangConfigAry) Reset() {
	*x = SpribeLangConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribeLangConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribeLangConfigAry) ProtoMessage() {}

func (x *SpribeLangConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribeLangConfigAry.ProtoReflect.Descriptor instead.
func (*SpribeLangConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{17}
}

func (x *SpribeLangConfigAry) GetAry() []*SpribeLangConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type SpribePlatformConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform Platform `protobuf:"varint,1,opt,name=Platform,proto3,enum=bit_casino_golang.Platform" json:"Platform,omitempty"` // 平台类型
	Code     string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                          // 名字
}

func (x *SpribePlatformConfig) Reset() {
	*x = SpribePlatformConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribePlatformConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribePlatformConfig) ProtoMessage() {}

func (x *SpribePlatformConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribePlatformConfig.ProtoReflect.Descriptor instead.
func (*SpribePlatformConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{18}
}

func (x *SpribePlatformConfig) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PlatformTypeNone
}

func (x *SpribePlatformConfig) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SpribePlatformConfigAry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ary []*SpribePlatformConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
}

func (x *SpribePlatformConfigAry) Reset() {
	*x = SpribePlatformConfigAry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_gen_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpribePlatformConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpribePlatformConfigAry) ProtoMessage() {}

func (x *SpribePlatformConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpribePlatformConfigAry.ProtoReflect.Descriptor instead.
func (*SpribePlatformConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{19}
}

func (x *SpribePlatformConfigAry) GetAry() []*SpribePlatformConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_table_gen_proto protoreflect.FileDescriptor

var file_table_gen_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x1a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x16, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x37,
	0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x61, 0x74, 0x69, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x22, 0x58, 0x0a,
	0x19, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x03, 0x41, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61,
	0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0xd4, 0x03, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63,
	0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x37, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x48, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x48, 0x6f, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61,
	0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x72, 0x65, 0x61, 0x12, 0x39, 0x0a, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x73,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73,
	0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x52, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x63,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x40,
	0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12,
	0x2f, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79,
	0x22, 0xf2, 0x01, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x69, 0x64, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x55, 0x69, 0x64, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x53, 0x70, 0x72, 0x69,
	0x62, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x53,
	0x70, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x4c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a,
	0x0e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x55, 0x72, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x44, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x31, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69,
	0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x76, 0x0a, 0x13, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x37, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e,
	0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x16, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x38, 0x0a,
	0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62, 0x69, 0x74,
	0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x72, 0x0a, 0x0f, 0x49, 0x6e, 0x6f, 0x75, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72,
	0x79, 0x12, 0x34, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x72, 0x0a, 0x0f, 0x49, 0x6e, 0x6f, 0x75, 0x74,
	0x4c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72,
	0x79, 0x12, 0x34, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x77, 0x0a, 0x14, 0x53, 0x70, 0x72, 0x69, 0x62,
	0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x37, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x54, 0x0a, 0x17, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x03, 0x41,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63,
	0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x53, 0x70, 0x72,
	0x69, 0x62, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x73, 0x0a, 0x10, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x13, 0x53,
	0x70, 0x72, 0x69, 0x62, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41,
	0x72, 0x79, 0x12, 0x35, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2e, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x73, 0x0a, 0x10, 0x53, 0x70, 0x72,
	0x69, 0x62, 0x65, 0x4c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c,
	0x0a, 0x13, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x35, 0x0a, 0x03, 0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x61, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x22, 0x63, 0x0a, 0x14,
	0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x37, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x73,
	0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x54, 0x0a, 0x17, 0x53, 0x70, 0x72, 0x69, 0x62, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x03,
	0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x74, 0x5f,
	0x63, 0x61, 0x73, 0x69, 0x6e, 0x6f, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x53, 0x70,
	0x72, 0x69, 0x62, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x03, 0x41, 0x72, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_table_gen_proto_rawDescOnce sync.Once
	file_table_gen_proto_rawDescData = file_table_gen_proto_rawDesc
)

func file_table_gen_proto_rawDescGZIP() []byte {
	file_table_gen_proto_rawDescOnce.Do(func() {
		file_table_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_table_gen_proto_rawDescData)
	})
	return file_table_gen_proto_rawDescData
}

var file_table_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_table_gen_proto_goTypes = []interface{}{
	(*CurrencyExchangeConfig)(nil),    // 0: bit_casino_golang.CurrencyExchangeConfig
	(*CurrencyExchangeConfigAry)(nil), // 1: bit_casino_golang.CurrencyExchangeConfigAry
	(*GameConfig)(nil),                // 2: bit_casino_golang.GameConfig
	(*GameConfigAry)(nil),             // 3: bit_casino_golang.GameConfigAry
	(*GlobalConfig)(nil),              // 4: bit_casino_golang.GlobalConfig
	(*GlobalConfigAry)(nil),           // 5: bit_casino_golang.GlobalConfigAry
	(*InoutCurrencyConfig)(nil),       // 6: bit_casino_golang.InoutCurrencyConfig
	(*InoutCurrencyConfigAry)(nil),    // 7: bit_casino_golang.InoutCurrencyConfigAry
	(*InoutGameConfig)(nil),           // 8: bit_casino_golang.InoutGameConfig
	(*InoutGameConfigAry)(nil),        // 9: bit_casino_golang.InoutGameConfigAry
	(*InoutLangConfig)(nil),           // 10: bit_casino_golang.InoutLangConfig
	(*InoutLangConfigAry)(nil),        // 11: bit_casino_golang.InoutLangConfigAry
	(*SpribeCurrencyConfig)(nil),      // 12: bit_casino_golang.SpribeCurrencyConfig
	(*SpribeCurrencyConfigAry)(nil),   // 13: bit_casino_golang.SpribeCurrencyConfigAry
	(*SpribeGameConfig)(nil),          // 14: bit_casino_golang.SpribeGameConfig
	(*SpribeGameConfigAry)(nil),       // 15: bit_casino_golang.SpribeGameConfigAry
	(*SpribeLangConfig)(nil),          // 16: bit_casino_golang.SpribeLangConfig
	(*SpribeLangConfigAry)(nil),       // 17: bit_casino_golang.SpribeLangConfigAry
	(*SpribePlatformConfig)(nil),      // 18: bit_casino_golang.SpribePlatformConfig
	(*SpribePlatformConfigAry)(nil),   // 19: bit_casino_golang.SpribePlatformConfigAry
	(Currency)(0),                     // 20: bit_casino_golang.Currency
	(Provider)(0),                     // 21: bit_casino_golang.Provider
	(GameType)(0),                     // 22: bit_casino_golang.GameType
	(Platform)(0),                     // 23: bit_casino_golang.Platform
	(LangType)(0),                     // 24: bit_casino_golang.LangType
}
var file_table_gen_proto_depIdxs = []int32{
	20, // 0: bit_casino_golang.CurrencyExchangeConfig.Currency:type_name -> bit_casino_golang.Currency
	0,  // 1: bit_casino_golang.CurrencyExchangeConfigAry.Ary:type_name -> bit_casino_golang.CurrencyExchangeConfig
	21, // 2: bit_casino_golang.GameConfig.Provider:type_name -> bit_casino_golang.Provider
	22, // 3: bit_casino_golang.GameConfig.GameType:type_name -> bit_casino_golang.GameType
	23, // 4: bit_casino_golang.GameConfig.Platforms:type_name -> bit_casino_golang.Platform
	20, // 5: bit_casino_golang.GameConfig.Currencys:type_name -> bit_casino_golang.Currency
	2,  // 6: bit_casino_golang.GameConfigAry.Ary:type_name -> bit_casino_golang.GameConfig
	4,  // 7: bit_casino_golang.GlobalConfigAry.Ary:type_name -> bit_casino_golang.GlobalConfig
	20, // 8: bit_casino_golang.InoutCurrencyConfig.Currency:type_name -> bit_casino_golang.Currency
	6,  // 9: bit_casino_golang.InoutCurrencyConfigAry.Ary:type_name -> bit_casino_golang.InoutCurrencyConfig
	22, // 10: bit_casino_golang.InoutGameConfig.GameType:type_name -> bit_casino_golang.GameType
	8,  // 11: bit_casino_golang.InoutGameConfigAry.Ary:type_name -> bit_casino_golang.InoutGameConfig
	24, // 12: bit_casino_golang.InoutLangConfig.LangType:type_name -> bit_casino_golang.LangType
	10, // 13: bit_casino_golang.InoutLangConfigAry.Ary:type_name -> bit_casino_golang.InoutLangConfig
	20, // 14: bit_casino_golang.SpribeCurrencyConfig.Currency:type_name -> bit_casino_golang.Currency
	12, // 15: bit_casino_golang.SpribeCurrencyConfigAry.Ary:type_name -> bit_casino_golang.SpribeCurrencyConfig
	22, // 16: bit_casino_golang.SpribeGameConfig.GameType:type_name -> bit_casino_golang.GameType
	14, // 17: bit_casino_golang.SpribeGameConfigAry.Ary:type_name -> bit_casino_golang.SpribeGameConfig
	24, // 18: bit_casino_golang.SpribeLangConfig.LangType:type_name -> bit_casino_golang.LangType
	16, // 19: bit_casino_golang.SpribeLangConfigAry.Ary:type_name -> bit_casino_golang.SpribeLangConfig
	23, // 20: bit_casino_golang.SpribePlatformConfig.Platform:type_name -> bit_casino_golang.Platform
	18, // 21: bit_casino_golang.SpribePlatformConfigAry.Ary:type_name -> bit_casino_golang.SpribePlatformConfig
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_table_gen_proto_init() }
func file_table_gen_proto_init() {
	if File_table_gen_proto != nil {
		return
	}
	file_enum_gen_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_table_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyExchangeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyExchangeConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutCurrencyConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutCurrencyConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutGameConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutGameConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutLangConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutLangConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeCurrencyConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeCurrencyConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeGameConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeGameConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeLangConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribeLangConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribePlatformConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_table_gen_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpribePlatformConfigAry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_table_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_gen_proto_goTypes,
		DependencyIndexes: file_table_gen_proto_depIdxs,
		MessageInfos:      file_table_gen_proto_msgTypes,
	}.Build()
	File_table_gen_proto = out.File
	file_table_gen_proto_rawDesc = nil
	file_table_gen_proto_goTypes = nil
	file_table_gen_proto_depIdxs = nil
}
